# ===================================================================================
# 🚀 DOCKER COMPOSE PARA PRODUÇÃO AZURE
# ===================================================================================
# Este arquivo usa PostgreSQL como serviço separado para produção
# Usado apenas para referência - no Azure usaremos PostgreSQL gerenciado

version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: apitodo_prod
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: MinhaSenh@123!
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin -d apitodo_prod"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    environment:
      FLASK_ENV: production
      SECRET_KEY: azure-secret-key-super-secure-2024
      JWT_SECRET_KEY: azure-jwt-key-super-secure-2024
      DATABASE_URL: postgresql://pgadmin:MinhaSenh@123!@db:5432/apitodo_prod
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data_prod: