name: CI/CD Pipeline - Build e push da Imagem Docker
# O gatilho: define QUANDO o robô deve executar
on:
    # O evento principal é o 'push'
    push:
        # E só nos importamos com pushes para a branch 'main'
        branches: ['main']
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: 1. Checkout do código
              uses: actions/checkout@v4

            - name: 2. Configurar Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            - name: 3. Instalar dependências
              run: |
                pip install -r requirements.txt
                pip install pytest # Instala a dependência de teste

            - name: 4. Rodar os testes com Pytest
              run: pytest

    build-e-push-imagem:
        runs-on: ubuntu-latest
        needs: test # Este job só roda se o job 'test' passar
        steps:
            - name: 1. Checkout do código
              uses: actions/checkout@v4

            - name: 2. Login no Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: 3. Build and Push da Imagem Docker
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: caiosfdev/projeto-api-devops:latest
    